name: Build WinForms EXE

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    defaults:
      run:
        working-directory: ArwToJpegGui
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore ArwToJpegGui.csproj

      - name: Publish single file exe
        run: >
          dotnet publish ArwToJpegGui.csproj
          -c Release
          -r win-x64
          -p:PublishSingleFile=true
          -p:SelfContained=true
          -p:PublishTrimmed=false

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ARWtoJPEGGui
          path: |
            ArwToJpegGui/bin/Release/net8.0-windows/win-x64/publish/*.exe
            ArwToJpegGui/bin/Release/net8.0-windows/win-x64/publish/tools/**
