# .github/workflows/build.yml
name: Build WinForms EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Publish single file exe
        run: >
          dotnet publish -c Release -r win-x64
          -p:PublishSingleFile=true
          -p:SelfContained=true
          -p:PublishTrimmed=false

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ARWtoJPEGGui
          path: |
            **/bin/Release/net8.0/win-x64/publish/*.exe
            **/bin/Release/net8.0/win-x64/publish/tools/**
            
